on:
  push:
    branches:
    - main

jobs:
  create-yarn-cache:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-shared

      - name: Install Dependencies
        run: yarn install --immutable
